feat: Components & Groups w. new Muscle structure in Arms & Legs
AnyBody/AMMR4-Beta pull request #31
Opened 2024-10-28 09:08 UTC by bkje14

PR to implement new `AnyComponentDefinitions` in the BodyModel. This replaces the old implementation with regex searching.

New Muscle groups are also implemented with the new `AnyComponentGroup` class.
This means that the Arm and Leg models have switched to the same folder structure as the Trunk model.
Individual muscle elements are collected into AnyFolders for AMS version < 8.2 and `AnyComponentGroup` for new AMS versions.

The "old" structure with muscles in a flat list can be activated with the new *temporary* BM switch: `BM_COMPATIBILITY_30_MUSCLE_STRUCTURE` - this will create ref objects to allow users to gracefully switch to the new structure. 

A few side quests got handled also:
- Moved the `...Trunk.Mesh` folder inside the `...Trunk.Abdominal` folder where it belongs
- Moved the `...Trunk.LayerConstraints` into the `...Trunk.Abdominal` where it belongs
- Reordered the objects inside `...ShoulderArm.Mus` so all none muscle objects are displayed at the bottom.
- disabling AnyFixedRefFrame for the `InterpolFunWithSPar.any` as I believe they are only a debug tool

2024-10-30 11:23 UTC, melund requested changes

2024-10-30 11:23 UTC, melund commented on Body/AAUHuman/LegTLEM/ammr_3.0_compatibility_structure.any
I think there are some muscles missing from the Leg compatibility list

2024-10-30 11:24 UTC, melund commented
Let us take the rest of the review tomorrow or next week. Whatever, you prefer.

2024-10-31 10:18 UTC, bkje14 commented on Body/AAUHuman/LegTLEM/ammr_3.0_compatibility_structure.any
I was missing all `AnyMuscleViaPoint` muscles :O 
They are added now!

2024-11-15 07:53 UTC, bkje14 commented
@melund The component & group PR in AMS has been merged now so there is support for this feature in AMS 8.2 now (Y)

2024-12-11 12:13 UTC, melund approved these changes

2024-12-11 13:21 UTC, merged